# lightning.pytorch==2.0.0
name: fma-s-44k_addnoise_wd1e-3
version: final-v0

seed_everything: 42
trainer:
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 300
  deterministic: true
  plugins:
    - AsyncCheckpointIO
  callbacks:
    - class_path: WandbSampleLoggerCallback
      init_args:
        train_log_interval: 1000
        val_log_interval: 5
        train_samples_per_batch: 10
        val_samples_per_batch: 10
        train_batches_per_epoch: 10
        val_batches_per_epoch: 10
  # profiler:
  #   class_path: SimpleProfiler
  #   init_args:
  #     filename: profile

model:
  class_path: DefaultModel
  init_args:
    net:
      class_path: net.eff.EfficientNet

    stft_params:
      n_fft: 2048
      hop_length: 512
      win_length: 2048
      center: true
      window: hann_window

    sr: 44100
    compression: 0.3

    criterion:
      class_path: MSELoss

data:
  class_path: FMADataModule
  init_args:
    root: data/fma_small_wav_44k
    batch_size: 8
    num_workers: 32
    sr: ${model.init_args.sr}
    metadata_path: data/fma_metadata
    subset: small
    val_eq_dir: random_walk_eqs_db
    noise_path: data/noise_samples_1367100_length_44100_hz.npz
    # transforms:
    #   class_path: DefaultTransforms

optimizer:
  class_path: AdamW
  init_args:
    lr: 1e-3
    weight_decay: 1e-2

lr_scheduler:
  class_path: CosineAnnealingLR
  init_args:
    T_max: ${trainer.max_epochs}

early_stopping:
  monitor: val/acc
  patience: 1000
  mode: max

model_ckpt:
  # dirpath: "gs://bucket-name[/extra-path]"
  monitor: val/loss
  mode: min
  auto_insert_metric_name: false
  filename: "best-epoch={epoch:02d}-val_loss={val/loss:.4f}"
